# ?? ?? ??
server:
  port: 8082

spring:
  datasource:
    #    url: jdbc:mysql://localhost:8080/test?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC
    username:
    password: 
    #password becareful
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# spring data jpa settings (got from youtube and doesn't work)
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: create